---
name: release-to-pypi
"on":
  push:
    tags:
      - '*'
jobs:
  build:
    name: release
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/og-binx-image-generator
    if: github.event.base_ref == 'refs/heads/main' || github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          python-version: 3.13
      - name: checkout
        run: git fetch --prune --unshallow
      - name: install environment
        run: |
          pip install build
          pip install -e .
      - name: build
        run: make build
      - name: upload to pypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages_dir: dist/
